### ISSUE TITLE
Social Media link config is back-to-front

### ISSUE THREAD

**Issue by phptek** [soulroll/silverstripe-eklektos#3]
Adding a Twitter account into the footer socials, the CMS description text reads "Twitter username (eg, http://twitter.com/username)" - where "username" is bold. So if I add a Twitter account in the CMS as "catalystnz", the generated link is `https://catalystnz`. I would expect it to render as per the CMS instructions: `https://twitter.com/catalystnz`

**Comment by soulroll** [comment]
Just been fixed and pushed to Bootstarter :)
